services:
  nextpoints:
    container_name: nextpoints
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    shm_size: 16G
    volumes:
      - ./:/workspace
    # command: python3 main.py
    command: bash
    stdin_open: true
    tty: true
    ports:
      - "10081:10081"
    restart: always
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:6
    container_name: nextpoints-redis
    restart: unless-stopped
